intranet/apps/api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import api_root
from ..announcements import api as announcements_api
from ..eighth.views import api as eighth_api
from ..emerg import api as emerg_api
from ..schedule import api as schedule_api
from ..users import api as users_api

urlpatterns = [
    url(r"^$", api_root, name="api_root"),
    url(r"^/announcements$", announcements_api.ListCreateAnnouncement.as_view(), name="api_announcements_list_create"),
    url(r"^/announcements/(?P<pk>[0-9]+)$", announcements_api.RetrieveUpdateDestroyAnnouncement.as_view(), name="api_announcements_detail"),
    url(r"^/blocks$", eighth_api.EighthBlockList.as_view(), name="api_eighth_block_list"),
    url(r"^/blocks/(?P<pk>[0-9]+)$", eighth_api.EighthBlockDetail.as_view(), name="api_eighth_block_detail"),
    url(r"^/classes/(?P<pk>.{6}-.{2})$", users_api.ClassDetail.as_view(), name="api_user_class_detail"),
    url(r"^/search/(?P<query>.+)$", users_api.Search.as_view(), name="api_user_search"),
    url(r"^/activities$", eighth_api.EighthActivityList.as_view(), name="api_eighth_activity_list"),
    url(r"^/activities/(?P<pk>[0-9]+)$", eighth_api.EighthActivityDetail.as_view(), name="api_eighth_activity_detail"),
    url(r"^/profile$", users_api.ProfileDetail.as_view(), name="api_user_myprofile_detail"),
    url(r"^/profile/(?P<pk>[0-9]+)$", users_api.ProfileDetail.as_view(), name="api_user_profile_detail"),
    url(r"^/profile/(?P<pk>[0-9]+)/picture$", users_api.ProfilePictureDetail.as_view(), name="api_user_profile_picture_default"),
    url(r"^/profile/(?P<pk>[0-9]+)/picture/(?P<photo_year>[a-zA-Z]+)$", users_api.ProfilePictureDetail.as_view(), name="api_user_profile_picture"),
    url(r"^/signups/user$", eighth_api.EighthUserSignupListAdd.as_view(), name="api_eighth_user_signup_list_myid"),
    url(r"^/signups/user/(?P<user_id>[0-9]+)$", eighth_api.EighthUserSignupListAdd.as_view(), name="api_eighth_user_signup_list"),
    url(r"^/signups/scheduled_activity/(?P<scheduled_activity_id>[0-9]+)$", eighth_api.EighthScheduledActivitySignupList.as_view(),
        name="api_eighth_scheduled_activity_signup_list"),
    url(r"^/schedule$", schedule_api.DayList.as_view(), name="api_schedule_day_list"),
    url(r"^/schedule/(?P<date>.*)$", schedule_api.DayDetail.as_view(), name="api_schedule_day_detail"),
    url(r"^/emerg$", emerg_api.emerg_status, name="api_emerg_status"),
]

intranet/apps/auth/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.index_view, name="index"),
    url(r"^login$", views.LoginView.as_view(), name="login"),
    url(r"^logout$", views.logout_view, name="logout"),
    url(r"^about$", views.about_view, name="about"),
]

intranet/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from intranet.apps.error.views import (handle_404_view, handle_500_view, handle_503_view)

admin.autodiscover()

urlpatterns = [
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/img/favicon.ico"), name="favicon"),
    url(r"^robots\.txt$", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    url(r"^manifest\.json$", RedirectView.as_view(url="/static/manifest.json"), name="chrome_manifest"),
    url(r"^serviceworker\.js$", TemplateView.as_view(template_name="serviceworker.js", content_type="text/javascript"), name="chrome_serviceworker"),
    url(r"^api", include("intranet.apps.api.urls"), name="api_root"),
    url(r"^", include("intranet.apps.auth.urls")),
    url(r"^announcements", include("intranet.apps.announcements.urls")),
    url(r"^eighth", include("intranet.apps.eighth.urls")),
    url(r"^events", include("intranet.apps.events.urls")),
    url(r"^files", include("intranet.apps.files.urls")),
    url(r"^groups", include("intranet.apps.groups.urls")),
    url(r"^polls", include("intranet.apps.polls.urls")),
    url(r"^search", include("intranet.apps.search.urls")),
    url(r"^profile", include("intranet.apps.users.urls")),
    url(r"^schedule", include("intranet.apps.schedule.urls")),
    url(r"^seniors", include("intranet.apps.seniors.urls")),
    url(r"^preferences", include("intranet.apps.preferences.urls")),
    url(r"^feedback", include("intranet.apps.feedback.urls")),
    url(r"^welcome", include("intranet.apps.welcome.urls")),
    url(r"^notifications", include("intranet.apps.notifications.urls")),
    url(r"^signage", include("intranet.apps.signage.urls")),
    url(r"^printing", include("intranet.apps.printing.urls")),
    url(r"^ionldap", include("intranet.apps.ionldap.urls")),
    url(r"^board", include("intranet.apps.board.urls")),
    url(r"^itemreg", include("intranet.apps.itemreg.urls")),
    url(r"^lostfound", include("intranet.apps.lostfound.urls")),
    url(r"^emailfwd", include("intranet.apps.emailfwd.urls")),
    url(r"^parking", include("intranet.apps.parking.urls")),
    url(r"^djangoadmin/doc/", include('django.contrib.admindocs.urls')),
    url(r"^djangoadmin/", include(admin.site.urls)),
    url(r"^oauth/", include("oauth2_provider.urls", namespace='oauth2_provider')),
    url(r"^oauth/$", RedirectView.as_view(url="/oauth/applications/"), name="oauth_redirect")
]

if settings.SHOW_DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

handler404 = handle_404_view
handler500 = handle_500_view
handler503 = handle_503_view  # maintenance mode

intranet/utils/urls.py
# -*- coding: utf-8 -*-

from urllib import parse


def add_get_parameters(url, parameters, percent_encode=True):
    """Utility function to add GET parameters to an existing URL.

    Args:
        parameters
            A dictionary of the parameters that should be added.
        percent_encode
            Whether the query parameters should be percent encoded.

    Returns:
        The updated URL.

    """
    url_parts = list(parse.urlparse(url))
    query = dict(parse.parse_qs(url_parts[4]))
    query.update(parameters)

    if percent_encode:
        url_parts[4] = parse.urlencode(query)
    else:
        url_parts[4] = "&".join([key + "=" + value for key, value in query.items()])

    return parse.urlunparse(url_parts)

intranet/apps/announcements/models.py
# -*- coding: utf-8 -*-

from datetime import datetime

from django.contrib.auth.models import Group as DjangoGroup
from django.db import models
from django.db.models import Manager, Q

from ..users.models import User
from ...utils.date import is_current_year


class AnnouncementManager(Manager):

    def visible_to_user(self, user):
        """Get a list of visible announcements for a given user (usually request.user).

        These visible announcements will be those that either have no
        groups assigned to them (and are therefore public) or those in
        which the user is a member.

        Apparently this .filter() call occasionally returns duplicates, hence the .distinct()...

        """

        return Announcement.objects.filter(Q(groups__in=user.groups.all()) |
                                           Q(groups__isnull=True) |
                                           Q(announcementrequest__teachers_requested=user) |
                                           Q(announcementrequest__user=user) |
                                           Q(user=user)).distinct()

    def hidden_announcements(self, user):
        """Get a list of announcements marked as hidden for a given user (usually request.user).

        These are all announcements visible to the user -- they have just decided to
        hide them.

        """
        ids = user.announcements_hidden.all().values_list("announcement__id")
        return Announcement.objects.filter(id__in=ids)


class AnnouncementUserMap(models.Model):
    """Represents mapping fields between announcements and users.

    These attributes would be a part of the Announcement model, but if they are,
    the last updated date is changed whenever a student sees or hides an announcement.

    Access these through announcement.user_map

    If you are checking to see whether a user has hidden an announcement, use:
        Announcement.objects.hidden_announcements(user)

    Attributes:
        announcement
            The one-to-one mapping between this object and the Announcement it is for
        users_hidden
            A many-to-many field of Users who have hidden this announcement
        users_seen
            A many-to-many field of Users who have seen this announcement

    """
    announcement = models.OneToOneField("Announcement", related_name="_user_map")
    users_hidden = models.ManyToManyField(User, blank=True, related_name="announcements_hidden")
    users_seen = models.ManyToManyField(User, blank=True, related_name="announcements_seen")

    def __str__(self):
        return "UserMap: {}".format(self.announcement.title)


class Announcement(models.Model):
    """Represents an announcement.

    Attributes:
        title
            The title of the announcement
        content
            The HTML content of the news post
        authors
            The name of the author
        added
            The date the announcement was added
        updated
            The most recent date the announcement was updated
        user_map
            An attribute corresponding with an AnnouncementUserMap object.
            A new object is automatically created if it does not exist.

    """

    objects = AnnouncementManager()

    title = models.CharField(max_length=127)
    content = models.TextField()
    author = models.CharField(max_length=63, blank=True)
    user = models.ForeignKey(User, null=True, blank=True)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    groups = models.ManyToManyField(DjangoGroup, blank=True)

    expiration_date = models.DateTimeField(auto_now=False, default=datetime(3000, 1, 1))

    notify_post = models.BooleanField(default=True)
    notify_email_all = models.BooleanField(default=False)

    pinned = models.BooleanField(default=False)

    def get_author(self):
        return self.author if self.author else self.user.full_name if self.user else None

    def __str__(self):
        return self.title

    @property
    def user_map(self):
        try:
            return self._user_map
        except AnnouncementUserMap.DoesNotExist:
            return AnnouncementUserMap.objects.create(announcement=self)

    @property
    def is_this_year(self):
        """Return whether the announcement was created after September 1st of this school year."""
        return is_current_year(self.added.date())

    def is_visible(self, user):
        return self in Announcement.objects.visible_to_user(user)

    _announcementrequest = None  # type: AnnouncementRequest

    @property
    def announcementrequest(self):
        if self._announcementrequest:
            return self._announcementrequest

        a = self.announcementrequest_set
        if a.count() > 0:
            ar = a.first()
            self._announcementrequest = ar
            return ar

    def is_visible_requester(self, user):
        return self.announcementrequest and (user in self.announcementrequest.teachers_requested.all())

    def is_visible_submitter(self, user):
        return (self.announcementrequest and user == self.announcementrequest.user) or self.user == user

    @property
    def dashboard_type(self):
        return "announcement"

    class Meta:
        ordering = ["-pinned", "-added"]


class AnnouncementRequest(models.Model):
    """Represents a request for an announcement.

    Attributes:
        title
            The title of the announcement
        content
            The HTML content of the news post
        notes
            Notes for the person who approves the announcement
        added
            The date the request was added
        updated
            The most recent date the request was updated
        user
            The user who submitted the request
        teachers_requested
            The teachers requested to approve the request
        teachers_approved
            The teachers who have approved the request
        posted
            ForeignKey to Announcement if posted
        posted_by
            The user (administrator) that approved the request
        rejected
            Boolean describing whether the post was rejected by
            an administrator. This will hide it.
        admin_email_sent
            Boolean describing whether an email was sent to an
            Intranet administrator to post the announcement.

    """

    title = models.CharField(max_length=127)
    content = models.TextField()
    author = models.CharField(max_length=63, blank=True)

    expiration_date = models.DateTimeField(auto_now=False, default=datetime(3000, 1, 1))
    notes = models.TextField(blank=True)

    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(User, null=True, blank=True, related_name="user")

    teachers_requested = models.ManyToManyField(User, blank=False, related_name="teachers_requested")
    teachers_approved = models.ManyToManyField(User, blank=True, related_name="teachers_approved")

    posted = models.ForeignKey(Announcement, null=True, blank=True)
    posted_by = models.ForeignKey(User, null=True, blank=True, related_name="posted_by")

    rejected = models.BooleanField(default=False)
    rejected_by = models.ForeignKey(User, null=True, blank=True, related_name="rejected_by")

    admin_email_sent = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-added"]

intranet/apps/emailfwd/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ..users.models import User


class SeniorEmailForward(models.Model):
    user = models.ForeignKey(User)
    email = models.EmailField()

    def __str__(self):
        return "{}".format(self.user)

intranet/apps/feedback/models.py
# -*- coding: utf-8 -*-
from django.db import models

from ..users.models import User


class Feedback(models.Model):
    user = models.ForeignKey(User)
    comments = models.CharField(max_length=50000)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return "{} - {}".format(self.user, self.date)

intranet/apps/lostfound/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ..users.models import User


class LostItem(models.Model):
    user = models.ForeignKey(User, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    last_seen = models.DateField()
    added = models.DateTimeField(auto_now_add=True)
    found = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        ordering = ["-added"]


class FoundItem(models.Model):
    user = models.ForeignKey(User, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    found = models.DateField()
    added = models.DateTimeField(auto_now_add=True)
    retrieved = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        ordering = ["-added"]

intranet/apps/notifications/models.py
# -*- coding: utf-8 -*-

import hashlib
import json

from django.db import models

from ..users.models import User


class NotificationConfig(models.Model):
    user = models.OneToOneField(User)
    gcm_token = models.CharField(max_length=250, blank=True, null=True)
    gcm_time = models.DateTimeField(blank=True, null=True)
    gcm_optout = models.BooleanField(default=False)

    android_gcm_rand = models.CharField(max_length=100, blank=True, null=True)

    @property
    def gcm_token_sha256(self):
        return hashlib.sha256(self.gcm_token.encode()).hexdigest()

    def __str__(self):
        return "{}".format(self.user)


class GCMNotification(models.Model):
    multicast_id = models.CharField(max_length=250)
    num_success = models.IntegerField(default=0)
    num_failure = models.IntegerField(default=0)
    sent_data = models.CharField(max_length=10000)
    sent_to = models.ManyToManyField(NotificationConfig)
    time = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)

    def __str__(self):
        return "{} at {}".format(self.multicast_id, self.time)

    @property
    def data(self):
        json_data = json.loads(self.sent_data)
        if json_data and "data" in json_data:
            return json_data["data"]
        return {}

intranet/apps/printing/models.py
# -*- coding: utf-8 -*-

from django.db import models

from ..users.models import User


class PrintJob(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    printer = models.CharField(max_length=100)
    file = models.FileField(upload_to="printing/")
    page_range = models.CharField(blank=True, max_length=100)
    time = models.DateTimeField(auto_now_add=True)
    printed = models.BooleanField(default=False)
    num_pages = models.IntegerField(default=0)
    duplex = models.BooleanField(default=True)

    def __str__(self):
        return "{} by {} to {}".format(self.file, self.user, self.printer)

intranet/templates/events/add_modify.html
{% extends "page_with_nav.html" %}
{% load staticfiles %}
{% load dates %}
{% load pipeline %}

{% block title %}
    {{ block.super }} - {{ action|title }} Event
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'vendor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/datetimepicker-2.4.5/jquery.datetimepicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/selectize.js-0.12.1/dist/js/standalone/selectize.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $("select#id_groups").selectize({
                plugins: ["remove_button"],
                placeholder: "Everyone"
            });

            $("#id_time").datetimepicker({
                lazyInit: true,
                format: "Y-m-d H:i:s"
            });

            $("#id_links").selectize({
                placeholder: "Links",
                create: true
            })
        });
    </script>
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/datetimepicker-2.4.5/jquery.datetimepicker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/selectize.js-0.12.1/dist/css/selectize.default.css' %}">
    {% stylesheet 'announcements.form' %}
{% endblock %}

{% block main %}
<div class="events announcements primary-content">
    <h2>
        {{ action_title }} Event
    </h2>
    <form action="/events/{{ action }}{% if id %}/{{ id }}{% endif %}" method="post">
    <table>
    {% csrf_token %}
    <tr><td colspan="2">
        {% if action == "add" %}
            <p>
                {% if is_events_admin %}
                    You can directly post an event to Intranet using this form.
                {% else %}
                    You may submit an event to be displayed on Intranet using this form. Please note that it will have to be approved by an administrator.
                {% endif %}
            </p>
            <p>
                Events posted should relate directly to the TJ community. Examples of this include special club meetings, bake sales, and school sporting events.
            </p>
            <br />
        {% endif %}
    </td></tr>
    {{ form.as_table }}
    <tr><td colspan="2">
        {% if id %}
            <a href="{% url 'delete_event' id %}" class="button">Delete</a>
        {% endif %}
        <input type="submit" style="width: 150px" /></td></tr>
    </table>
    </form>
</div>
<script type="text/javascript">
    // name of <textarea> is content
    CKEDITOR.replace("id_description", {
        width: "600px"
    });
</script>
{% endblock %}

intranet/templates/events/delete.html
{% extends "page_with_nav.html" %}
{% load staticfiles %}
{% load dates %}

{% block title %}
    {{ block.super }} - {{ action|title }} Event
{% endblock %}

{% block js %}
    {{ block.super }}
{% endblock %}

{% block css %}
    {{ block.super }}
{% endblock %}

{% block main %}
<div class="events primary-content">
    <h3>Are you sure you want to delete this event?</h3>
    <b>{{ event.title }}</b>
    <br />
    <br />
    {{ event.description|safe }}
    <br />
    <br />
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ event.id }}" />
        <a class="button" href="{% url 'events' %}">Cancel</a>
        <input type="submit" value="Delete" />
    </form>
</div>
{% endblock %}

intranet/templates/events/event.html
{% load dates %}
{% load staticfiles %}

{% if event.scheduled_activity and announcement %}
    {% with schact=event.scheduled_activity link_to_scheduled_activity=1 %}
        {% include "events/scheduled_activity.html" %}
    {% endwith %}
{% endif %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/vendor/jquery.timeago.js' %}"></script>
{% endblock %}

<div class="event{% if hide_events and event.id in user_hidden_events %} hidden{% endif %}" data-id="{{ event.id }}">
    <h3>
        {% if show_icon %}
            <i class="fa fa-calendar dashboard-item-icon" title="Event"></i>
        {% endif %}

        {% if not event.approved %}<span style="color: red">UNAPPROVED:</span>{% endif %}
        {% if link_to_event %}
            <a href="{% url 'event' event.id %}" class="event-link">
                {{ event.title }}
            </a>
        {% else %}    
            {{ event.title }}
        {% endif %}

            <div class="event-icon-wrapper">
                {% if hide_events %}
                    <a href="#" class="event-toggle">
                    {% if event.id in user_hidden_events %}
                        <i class="announcement-icon fa fa-expand" title="You have hidden this event. Click to show." data-visible-title="This event is visible. Click to hide." hidden-title="You have hidden this event. Click to show."></i>
                    {% else %}
                        <i class="announcement-icon fa fa-compress" title="This event is visible. Click to hide." data-visible-title="This event is visible. Click to hide." data-hidden-title="You have hidden this event. Click to show."></i>
                    {% endif %}
                    </a>
                {% endif %}
                    <a href="{% url 'event' event.id %}" title="Event permalink">
                        <i class="fa fa-share-square-o"></i>
                    </a>
                {% if events_admin %}
                    <a href="{% url 'modify_event' event.id %}">
                        <i class="event-icon fa fa-pencil"></i>
                    </a>
                    <a href="{% url 'delete_event' event.id %}" class="event-delete">
                        <i class="event-icon fa fa-trash-o"></i>
                    </a>
                {% endif %}
            </div>
    </h3>

    <div class="event-metadata">
        by {{ event.user.full_name|escape }} {% if event.show_fuzzy_date %}&bull; <time class="timeago" datetime="{{ event.time|date:'c' }}">{{ event.time|fuzzy_date|capfirst }}</time>{% endif %} &bull; {{ event.time|date:"l, F j, Y"}}{% if event.time|date:"P" != "midnight" %} {{ event.time|date:"P" }}{% endif %} &bull; for
        {% for group in event.groups.all %}
            {{ group }}
            {% if not forloop.last %},{% endif %}
        {% empty %}
            everyone
        {% endfor %}
    </div>
    <div class="event-toggle-content"{% if hide_events and event.id in user_hidden_events %} style="display:none"{% endif %}>
        {% if event.scheduled_activity and not announcement %}
            {% with schact=event.scheduled_activity link_to_scheduled_activity=1 %}
                {% include "events/scheduled_activity.html" %}
            {% endwith %}
        {% endif %}

        {% if event.announcement and not announcement %}
            {% with announcement=event.announcement link_to_announcement=1 %}
                {% include "announcements/announcement.html" %}
            {% endwith %}
        {% endif %}
        
        <div class="event-content">
            {{ event.description|safe }}
        </div>
        {% if show_attend %}
            <form action="{% url 'join_event' event.id %}" method="post" name="no-attend-form-{{ event.id }}">
                {% csrf_token %}
                <input type="hidden" name="attending" value="false" />
            </form>

            <form action="{% url 'join_event' event.id %}" method="post" name="attend-form-{{ event.id }}">
                {% csrf_token %}
                <input type="hidden" name="attending" value="true" />
            </form>
        {% endif %}

        {% if is_events_admin %}
            <table class="event-approve-table">
                <tr>
                    <td>
                    {% if not event.approved %}
                        <form action="{% url 'events' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="approve" value="{{ event.id }}" />
                            <input type="submit" value="Approve" class="small-button" />
                        </form>
                    {% else %}
                        Approved by {{ event.approved_by.full_name }}.
                    {% endif %}
                    </td>
                    <td>
                    {% if not event.approved %}
                        <form action="{% url 'events' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="reject" value="{{ event.id }}" />
                            <input type="submit" value="Reject" class="small-button" />
                        </form>
                    {% elif event.rejected %}
                        Rejected by {{ event.rejected_by.full_name }}.
                    {% endif %}
                    </td>
                </tr>
            </table>
        {% endif %}

        {% if event.show_attending %}
        <div class="bottom-row{% if show_attend %} show-attend{% endif %}">
            <span class="signup-status">
                People attending: {{ event.attending.count }}
                {% if show_attend %}
                <a href="{% url 'event_roster' event.id %}" class="button small-button view-roster-button">
                    View Roster
                </a>
                {% endif %}
            </span>

            {% if request.user in event.attending.all %}
                <span class="attend-status">
                    You are <b style="color: green">attending</b> this event. 
                    {% if show_attend %}
                        <a href="#" data-form-submit="no-attend-form-{{ event.id }}" class="button small-button no-attend-button">
                            <i class="fa fa-times"></i>
                            Don't Attend
                        </a>
                    {% endif %}
                </span>
            {% else %}
                <span class="attend-status">
                    You are <b style="color: red">not attending</b> this event. 
                    {% if show_attend %}
                        <a href="#" data-form-submit="attend-form-{{ event.id }}" class="button small-button attend-button">
                            <i class="fa fa-check"></i>
                            Attend
                        </a>
                    {% endif %}
                </span>
            {% endif %}
        </div>
        {% endif %}
    </div>

</div>

intranet/templates/events/events.html
{% extends "page_with_nav.html" %}
{% load staticfiles %}

{% block title %}
    {{ block.super}} - Events
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/events.css' %}" />
{% endblock %}

{% block main %}
    <div class="primary-content" style="background-color: white; padding: 30px; border-radius: 5px; border: 1px solid rgb(216, 216, 216); max-width: 400px;">
        <i class="fa fa-calendar" style="font-size: 50px; margin-right: 10px;"></i> <span style="font-size: 50px;">Events</span>
        <div>
            <h3>Events is still in the works &mdash; Coming Fall 2015!</h3>
            <p class="narrow-paragraph">Events is a central student-run calendar of things happening at TJ. Add your club's bake sale or other special activities to promote your club and to get more involved in activities at TJ.</p>
            <p>Have a suggestion for Events? Tell us at <a href="mailto:intranet@tjhsst.edu">intranet@tjhsst.edu</a>.</p>
        </div>
    </div>
{% endblock %}

intranet/templates/events/home.html
{% extends "page_with_nav.html" %}
{% load staticfiles %}
{% load pipeline %}

{% block title %}
    {{ block.super }} - Events
{% endblock %}

{% block css %}
    {{ block.super }}
    {% stylesheet 'dashboard' %}
    {% stylesheet 'events' %}
{% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
    $(function() {
        $("[data-form-submit]").click(function() {
            var name = $(this).attr("data-form-submit");
            document.forms[name].submit();
        });
    });
    </script>
{% endblock %}

{% block main %}
    <div class="primary-content events">
        <h2>Events</h2>
        <div class="button-container">
            {% if is_events_admin %}
                <a href="?show_all=1" class="button">
                    Show All
                </a>
            {% endif %}

            {% if is_events_admin %}
                <a href="{% url 'add_event' %}" class="button">
                    <i class="fa fa-bullhorn"></i>
                    Add
                </a>
            {% else %}
                <a href="{% url 'request_event' %}" class="button">
                    <i class="fa fa-bullhorn"></i>
                    Submit
                </a>
            {% endif %}
        </div>

        <div class="events-container">
        {% for category in events %}
            {% if category.events %}
                <h2 class="category">{{ category.title }}:</h2>
            {% endif %}

            {% for event in category.events %}
                {% include "events/event.html" %}
            {% endfor %}
        {% endfor %}

        {% if num_events == 0 %}
            <div class="event">
                There are no events to display at this time.
            </div>
        {% endif %}

        {% if start_num > 0 %}
            <a href="?start={{ prev_page }}" class="button" style="float:left">&larr; Newer Posts</a>
        {% endif %}
        {% if more_events %}
            <a href="?start={{ end_num }}" class="button" style="float:right">Older Posts &rarr;</a>
        {% endif %}
    </div>

    </div>
{% endblock %}

intranet/templates/events/tjstar_widget.html
<div class="widget tjstar-widget">
    <div class="widget-title">
        <h2>
            tjSTAR Schedule
        </h2>
    </div>
    <div class="widget-content">
        <iframe src="https://apps.tjhsst.edu/tjstar/widget/{{ tjstar_uuid }}" style="width: 100%;height: 150px;overflow: hidden" scrolling="no"></iframe>  
    </div>
</div>